# ==============================================================================
# XPoSE-seq relapse GO dot plot
# Plots UPREGULATED GO terms from tables generated by 01_run_go.R.
# ==============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(readr)
  library(ggplot2)
  library(stringr)
})

if (!requireNamespace("GO.db", quietly = TRUE)) {
  stop("Package 'GO.db' is required. Install with BiocManager::install('GO.db').")
}
if (!requireNamespace("AnnotationDbi", quietly = TRUE)) {
  stop("Package 'AnnotationDbi' is required.")
}

# Configuration ----------------------------------------------------------
# This reproduces the attached final GO plot configuration.
analysis_name <- "RT_active_RT_nonactive_vmPFC"
analysis_label <- "vmPFC_RT"
ontology <- "MF"
direction <- "up"

go_root <- "output/04_relapse_transcriptional_characterization/03_go"
analysis_root <- file.path(go_root, analysis_name)
output_dir <- file.path(go_root, paste0("plot_", analysis_label, "_", ontology, "_up"))
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

biological_cluster_order <- c(
  "ITL23", "ITL5", "ITL6", "ITvm", "CTL6", "CTL6b", "ETL5", "NPL5",
  "Pvalb", "PvalbChand", "Sst", "SstChodl", "Sncg", "Vip", "Lamp5"
)

plot_clusters <- c("ITL23", "ITL5", "ITL6", "ITvm", "CTL6", "ETL5", "NPL5", "Pvalb", "Sst")
curated_terms <- NULL
top_n_if_uncurated <- 15
significance_threshold <- 0.05
x_label_wrap_threshold <- 24

panel_width <- 2.0
panel_height <- 1.0
outer_padding <- 0.04
x_label_angle <- 55

color_low <- "#F7E6ED"
color_high <- "#2D00FF"
color_nonsignificant <- "white"
outline_nonsignificant <- "grey55"
outline_significant <- "grey30"
dot_size_range <- c(1.5, 5.5)
enrichment_display_floor <- 1

# Read raw GO tables -----------------------------------------------------
raw_go_path <- function(cluster) {
  file.path(
    analysis_root,
    cluster,
    "02_GO",
    paste0(cluster, "_", ontology, "_", direction, "_combined_raw.csv")
  )
}

available <- plot_clusters[file.exists(vapply(plot_clusters, raw_go_path, character(1)))]
if (length(available) == 0) stop("No requested GO files were found in: ", analysis_root)

raw_all <- bind_rows(lapply(available, function(cluster) {
  read_csv(raw_go_path(cluster), show_col_types = FALSE) %>%
    transmute(
      cluster = cluster,
      GO.ID = as.character(GO.ID),
      Term_raw = as.character(Term),
      Annotated = as.numeric(Annotated),
      Significant = as.numeric(Significant),
      Expected = as.numeric(Expected),
      EnrichmentScore = as.numeric(EnrichmentScore),
      p_elim = as.numeric(p_elim),
      BH = as.numeric(BH_elim)
    )
})) %>%
  filter(!is.na(GO.ID), nzchar(GO.ID)) %>%
  group_by(cluster, GO.ID) %>%
  arrange(BH, .by_group = TRUE) %>%
  slice_head(n = 1) %>%
  ungroup()

# Select terms -----------------------------------------------------------
if (!is.null(curated_terms) && length(curated_terms) > 0) {
  keep_ids <- curated_terms[curated_terms %in% raw_all$GO.ID]
} else {
  keep_ids <- raw_all %>%
    filter(
      !is.na(BH), is.finite(BH),
      !is.na(EnrichmentScore), is.finite(EnrichmentScore)
    ) %>%
    group_by(GO.ID) %>%
    summarise(
      best_BH = min(BH, na.rm = TRUE),
      best_enrichment = max(EnrichmentScore, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    arrange(best_BH, desc(best_enrichment), GO.ID) %>%
    slice_head(n = top_n_if_uncurated) %>%
    pull(GO.ID)
}

if (length(keep_ids) == 0) stop("No GO terms were available for plotting.")

# Recover complete GO names ---------------------------------------------
term_lookup <- raw_all %>%
  filter(GO.ID %in% keep_ids) %>%
  distinct(GO.ID, .keep_all = TRUE) %>%
  transmute(GO.ID, Term_raw)

term_lookup$Term <- vapply(term_lookup$GO.ID, function(go_id) {
  obj <- tryCatch(GO.db::GOTERM[[go_id]], error = function(e) NULL)
  if (is.null(obj)) return(NA_character_)
  val <- tryCatch(AnnotationDbi::Term(obj), error = function(e) NA_character_)
  if (length(val) == 0 || is.na(val[1]) || !nzchar(val[1])) NA_character_ else as.character(val[1])
}, character(1))

term_lookup <- term_lookup %>%
  mutate(
    Term = if_else(is.na(Term) | !nzchar(Term), Term_raw, Term),
    label = vapply(Term, function(x) {
      if (is.na(x) || nchar(x) <= x_label_wrap_threshold) return(x)
      words <- strsplit(x, "[[:space:]]+")[[1]]
      if (length(words) < 2) return(x)
      breaks <- seq_len(length(words) - 1)
      score <- vapply(breaks, function(k) {
        max(
          nchar(paste(words[seq_len(k)], collapse = " ")),
          nchar(paste(words[(k + 1):length(words)], collapse = " "))
        )
      }, numeric(1))
      k <- breaks[which.min(score)]
      paste0(
        paste(words[seq_len(k)], collapse = " "),
        "\n",
        paste(words[(k + 1):length(words)], collapse = " ")
      )
    }, character(1))
  )

keep_ids <- keep_ids[keep_ids %in% term_lookup$GO.ID]
term_order <- term_lookup$label[match(keep_ids, term_lookup$GO.ID)]

# Complete cluster x term table -----------------------------------------
plot_values <- raw_all %>%
  filter(GO.ID %in% keep_ids) %>%
  select(cluster, GO.ID, Annotated, Significant, Expected, EnrichmentScore, p_elim, BH)

plot_all <- crossing(cluster = available, GO.ID = keep_ids) %>%
  left_join(plot_values, by = c("cluster", "GO.ID")) %>%
  left_join(term_lookup %>% select(GO.ID, Term, label), by = "GO.ID") %>%
  mutate(
    tested = !is.na(EnrichmentScore) & is.finite(EnrichmentScore) & !is.na(BH) & is.finite(BH),
    significant = tested & BH < significance_threshold,
    enrichment_display = if_else(tested, pmax(EnrichmentScore, enrichment_display_floor), NA_real_),
    negative_log10_BH = if_else(
      significant,
      -log10(pmax(BH, .Machine$double.xmin)),
      NA_real_
    ),
    cluster = factor(cluster, levels = rev(available)),
    label = factor(label, levels = term_order)
  )

write_csv(
  plot_all %>% mutate(cluster = as.character(cluster), label = as.character(label)),
  file.path(output_dir, "GO_dotplot_values.csv")
)

write_csv(
  term_lookup %>%
    filter(GO.ID %in% keep_ids) %>%
    mutate(selection_order = match(GO.ID, keep_ids)) %>%
    arrange(selection_order),
  file.path(output_dir, "GO_selected_terms.csv")
)

# Plot -------------------------------------------------------------------
pt <- function(x) x / 2.835

theme_publication <- theme_classic(base_size = 7, base_family = "Arial") +
  theme(
    axis.line = element_line(linewidth = pt(0.5), colour = "black"),
    axis.ticks = element_line(linewidth = pt(0.5), colour = "black"),
    axis.ticks.length = grid::unit(1.5, "pt"),
    axis.text = element_text(size = 7, colour = "black"),
    axis.text.x = element_text(
      size = 7, angle = x_label_angle, hjust = 1, vjust = 1,
      lineheight = 0.88, margin = margin(t = 2.5, unit = "pt")
    ),
    axis.title = element_text(size = 8, colour = "black"),
    legend.position = "right",
    legend.title = element_text(size = 7),
    legend.text = element_text(size = 7),
    panel.grid.major = element_line(linewidth = pt(0.25), colour = "grey94"),
    panel.grid.minor = element_blank(),
    plot.title = element_blank(),
    plot.subtitle = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank()
  )

size_values <- plot_all$enrichment_display[is.finite(plot_all$enrichment_display)]
if (length(size_values) == 0) stop("No finite enrichment values available for plotting.")
size_limits <- range(size_values)
if (diff(size_limits) == 0) size_limits <- size_limits + c(-0.5, 0.5)

sig_values <- plot_all$negative_log10_BH[is.finite(plot_all$negative_log10_BH)]
color_limits <- if (length(sig_values) > 0) range(sig_values) else c(-log10(significance_threshold), -log10(significance_threshold) + 1)
if (diff(color_limits) == 0) color_limits <- color_limits + c(-0.5, 0.5)

p <- ggplot(plot_all, aes(x = label, y = cluster)) +
  geom_point(
    data = plot_all %>% filter(tested, !significant),
    aes(size = enrichment_display),
    shape = 21,
    fill = color_nonsignificant,
    colour = outline_nonsignificant,
    stroke = pt(0.25)
  ) +
  geom_point(
    data = plot_all %>% filter(significant),
    aes(size = enrichment_display, fill = negative_log10_BH),
    shape = 21,
    colour = outline_significant,
    stroke = pt(0.25)
  ) +
  scale_fill_gradient(
    low = color_low,
    high = color_high,
    limits = color_limits,
    oob = scales::squish,
    name = expression(-log[10](BH))
  ) +
  scale_size_continuous(
    range = dot_size_range,
    limits = size_limits,
    name = "Enrichment"
  ) +
  scale_x_discrete(limits = term_order, drop = FALSE) +
  scale_y_discrete(limits = rev(available), drop = FALSE) +
  labs(x = NULL, y = NULL) +
  theme_publication

# Fix matrix panel at 2 x 1 inches while allowing labels/legends outside it.
grob <- ggplotGrob(p)
panel_rows <- grob$layout[grepl("^panel", grob$layout$name), , drop = FALSE]
panel_cols <- sort(unique(unlist(mapply(seq, panel_rows$l, panel_rows$r, SIMPLIFY = FALSE))))
panel_rws <- sort(unique(unlist(mapply(seq, panel_rows$t, panel_rows$b, SIMPLIFY = FALSE))))
grob$widths[panel_cols] <- grid::unit(panel_width / length(panel_cols), "in")
grob$heights[panel_rws] <- grid::unit(panel_height / length(panel_rws), "in")

measure_file <- tempfile(fileext = ".pdf")
if (capabilities("aqua")) {
  quartz(type = "pdf", file = measure_file, width = 8, height = 8, family = "Arial", pointsize = 7)
} else {
  pdf(file = measure_file, width = 8, height = 8, family = "Helvetica", pointsize = 7, useDingbats = FALSE)
}
grid::grid.newpage()
grid::grid.draw(grob)
content_width <- grid::convertWidth(sum(grob$widths), "in", valueOnly = TRUE)
content_height <- grid::convertHeight(sum(grob$heights), "in", valueOnly = TRUE)
dev.off()
unlink(measure_file)

pdf_width <- content_width + 2 * outer_padding
pdf_height <- content_height + 2 * outer_padding
pdf_file <- file.path(output_dir, paste0(analysis_label, "_GO_", ontology, "_UP_only.pdf"))

if (capabilities("aqua")) {
  quartz(type = "pdf", file = pdf_file, width = pdf_width, height = pdf_height, family = "Arial", pointsize = 7)
} else {
  pdf(file = pdf_file, width = pdf_width, height = pdf_height, family = "Helvetica", pointsize = 7, useDingbats = FALSE)
}
grid::grid.newpage()
grid::grid.draw(grob)
dev.off()

message("GO plot complete: ", pdf_file)
