#' Get Count Tables
#'
#' @param data_lst list of searot objects for dataser, generated by 
#'                 'make_cluster_list'
#' @param clust_vect vector of clusters for object, generated by 'Kowalski'
#' @param object SE, used to make allset
#' @param dataname name of data, used to make all_tbl
#'
#' @return the "MEGA" table that contains all the count tables
#' @export
#'
#' @examples
#' #Makes count tables for the requested clusters for glut object
#' mega_tbl <- get_cnt_tbls(glut_lst, glut_dat, glut, "Glut")
get_cnt_tbls <- function(data_lst, clust_vect, object, dataname){
  
  #Will hold all the tables
  furniture <- matrix(1:length(data_lst[[1]]@assays[["RNA"]]@counts@Dimnames[[1]]), ncol = 1)
  
  #makes a count table for each cluster
  for (i in 1:length(data_lst)){
    #pseudobulks and temporarily stores
    bulk_var <- to_pseudobulk(
      data_lst[[i]], #The source of what we're generating a count
      replicate_col = "ratID",
      cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
      label_col = "group"
    )
    
    #subset the cluster to test, here they are combined into one called "0"
    cnt_tbl <- bulk_var[[as.character(clust_vect[i])]]
    
    #Makes 'dummy' col and names to mark it
    if (i != 1){
      furniture <- cbind(furniture, 1:nrow(furniture))
      names(furniture)[ncol(furniture)] <- as.character(names(data_lst)[i])
      #First col = special case as mat is unpopulated
    }else {
      colnames(furniture)[1] <- as.character(names(data_lst)[i])
    }
    
    #adds new data to furniture
    furniture <- cbind(furniture, cnt_tbl)
  }
  
  #Makes the element with all the data
  allset <- FindClusters(object, resolution = 0)
  Idents(allset) <- 'group'
  allset <- subset(allset, idents = levels(data_lst[[1]])) # This may not be replicable but it works here
  
  #pseudobulks the all 
  all_dat <- to_pseudobulk(
    allset, #The source of what we're generating a count
    replicate_col = "ratID",
    cell_type_col = "seurat_clusters", # this is required, could merge as 1 to run
    label_col = "group"
  )
  
  #Turns that all into a table
  all_tbl <- all_dat[["0"]]  # <- The "0" was an inference so it may not work elsewhere
  
  #Names sect and adds to mega table
  furniture <- cbind(furniture, 1:nrow(furniture))
  names(furniture)[ncol(furniture)] <- paste("all", dataname, sep = "")
  furniture <- cbind(furniture, all_tbl)
  
  #returns Mega Table, the IKEA bulk order
  return(furniture)
}