#!/usr/bin/env Rscript
# XPoSE-seq: collect POC downsampling differential-expression jobs
#
# Combines per-job summaries and iteration tallies into long and Prism-ready
# wide tables after the Biowulf swarm has completed.
#
# Usage:
#   Rscript 04_collect_downsample.R --out_dir \
#     output/03_differential_expression/02_downsample_de/run_<run_id>

suppressPackageStartupMessages({
  library(optparse)
  library(dplyr)
  library(tidyr)
  library(readr)
  library(ggplot2)
})

opt <- parse_args(OptionParser(option_list = list(
  make_option(
    "--out_dir",
    type = "character",
    help = "Output folder generated by the downsampling swarm"
  )
)))

if (is.null(opt$out_dir)) {
  stop("--out_dir is required")
}

# Gather per-job outputs --------------------------------------------------
summary_files <- list.files(
  file.path(opt$out_dir, "summary"),
  pattern = "^summary_.*\\.csv$",
  full.names = TRUE
)

tally_files <- list.files(
  file.path(opt$out_dir, "tally"),
  pattern = "^tally_.*\\.csv$",
  full.names = TRUE
)

if (length(summary_files) == 0) {
  stop("No summary CSVs found in ", opt$out_dir)
}

summary_df <- bind_rows(lapply(summary_files, read_csv, show_col_types = FALSE)) %>%
  arrange(cluster, percentage)

tally_long <- bind_rows(lapply(tally_files, read_csv, show_col_types = FALSE)) %>%
  arrange(cluster, percentage, iteration)

percentage_order <- sort(unique(summary_df$percentage))

# Prism-ready wide matrices ----------------------------------------------
average_wide <- summary_df %>%
  select(cluster, percentage, mean_DE) %>%
  pivot_wider(names_from = percentage, values_from = mean_DE) %>%
  select(cluster, all_of(as.character(percentage_order))) %>%
  arrange(cluster)

sd_wide <- summary_df %>%
  select(cluster, percentage, sd_DE) %>%
  pivot_wider(names_from = percentage, values_from = sd_DE) %>%
  select(cluster, all_of(as.character(percentage_order))) %>%
  arrange(cluster)

write_csv(summary_df, file.path(opt$out_dir, "de_summary_long.csv"))
write_csv(tally_long, file.path(opt$out_dir, "de_tally_long.csv"))
write_csv(average_wide, file.path(opt$out_dir, "iteration_plot_sum_average.csv"))
write_csv(sd_wide, file.path(opt$out_dir, "iteration_plot_stdev.csv"))

# Overview plot -----------------------------------------------------------
p <- ggplot(
  summary_df,
  aes(percentage, mean_DE, color = cluster, group = cluster)
) +
  geom_line() +
  geom_point() +
  geom_errorbar(
    aes(ymin = mean_DE - sd_DE, ymax = mean_DE + sd_DE),
    width = 2
  ) +
  labs(
    x = "% active nuclei in NC pool",
    y = "Mean DE genes (adjusted P < 0.05)"
  ) +
  theme_classic()

ggsave(
  file.path(opt$out_dir, "de_by_active_fraction.png"),
  p,
  width = 9,
  height = 6,
  dpi = 300
)
