---
title: "02_Clustering"
author: "Katherine Savell"
date: "2023-03-14"
output: html_document
---

## Set knitting settings

```{r Setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Load packages

```{r message = FALSE}
library(Seurat)
library(ggplot2)
library(dplyr)
library(clustree)
library(harmony)
library(tidyverse)
library(future)

#set parallel conditions, do 1/2 or n - 2 the number of cores you have
plan('multisession', 
     workers = 3)
```

## Load combined Seurat object

The combined object has all metadata assigned and filtered out:
- multiplex and undefined Sample tag calls
- nuclei with < 50 features
```{r message=FALSE}
load("/Users/savellke/Documents/Analysis/mm10_exp1/mm10-LO_combined_09302022.RData")
```

## QC plots of imported Seurat object

```{r}
Idents(combined) <- "orig.ident"
VlnPlot(combined, 
        features = c("nFeature_RNA", "nCount_RNA"), 
        ncol = 2)

Idents(combined) <- "Sample_tag"
VlnPlot(combined, 
        features = c("nFeature_RNA", "nCount_RNA"), 
        ncol = 2)

Idents(combined) <- "group"
VlnPlot(combined, 
        features = c("nFeature_RNA", "nCount_RNA"), 
        ncol = 2)

Idents(combined) <- "sex"
VlnPlot(combined, 
        features = c("nFeature_RNA", "nCount_RNA"), 
        ncol = 2)
```
## First clustering iteration
```{r}
combined <- combined %>%
  NormalizeData() %>%
  FindVariableFeatures(selection.method = "vst", 
                       nfeatures = 2000) %>%
  ScaleData(verbose = FALSE) %>%
  RunPCA(ndims.print = 1:50, 
         nfeatures.print = 50) %>%
  FindNeighbors(dims = 1:50) %>% 
  RunUMAP(reduction = "pca", 
          dims = 1:50)
```
```{r}
combined <- FindClusters(combined, 
                         resolution = 5)
DimPlot(combined, 
        reduction = "umap", 
        label = TRUE, 
        repel = TRUE)
```

#Changing UMAP Colors to Allen Atlas Cluster Colors 
#Load Subsets 
```{r}
setwd("/Users/woodskad/Desktop/Analysis/S1/")
load("/Users/woodskad/Desktop/Analysis/S1/Robject/glut_subset_forthpipe_11102022.RData")
load("/Users/woodskad/Desktop/Analysis/S1/Robject/gaba_subset_forthpipe_03142023.RData")
```


#UMAP Glut Subset. 
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/F2_panels/UMAPs w: AA colors/GlutUMAPV2.pdf",
    width = 10,
    height = 10)
DimPlot(glut.subset2, 
        group.by = "seurat_clusters", 
        cols = c( "#64C7C8","#41B75F",  "#2C8CB9", "#0A5B8C", "#3C9E64", "#6F499D"),
        shuffle = T) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```

#UMAP GABA Subset. 
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/F2_panels/UMAPs w: AA colors/GABAUMAP.pdf",
    width = 10,
    height = 10)
DimPlot(gaba.subset2, 
        group.by = "seurat_clusters", 
        cols = c( "#E66027","#F8991D","#C03C82", "#A669AB", "#C52126",  "#DB808C", "#B0B235"),
        shuffle = T) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```