---
title: "02_CreateObjectWithAllMetadata"
author: "Kareem"
date: "2023-06-20"
output: html_document
---
## Set knitting settings

```{r Setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Load packages

```{r LoadPackages}
library(Seurat)
library(ggplot2)
library(dplyr)
```

## Set working directory. Import data, create Seurat object, and assign sample tag call to each nuclei.
```{r import}
# set working directory where the raw data files are found
setwd("~/MakeObject") 

# Read gene count data tables in 
counts.C1 <- read.table("~/MakeObject/Combined_cart1-good-only_RSEC_MolsPerCell.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)
counts.C2 <- read.table("~/MakeObject/Combined_cart2-good-only_RSEC_MolsPerCell.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)

# Import and add sample tag identification and format to one column
tags.C1 <- read.table("~/MakeObject/cart1-good-only_Sample_Tag_Calls.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)
tags.C2 <- read.table("~/MakeObject/cart2-good-only_Sample_Tag_Calls.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)

#Import Sample tag reads
STreads.C1 <- read.table("~/MakeObject/cart1-good-only_Sample_Tag_ReadsPerCell.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)
STreads.C2 <- read.table("~/MakeObject/cart2-good-only_Sample_Tag_ReadsPerCell.csv", sep = ",", skip = 7, header = TRUE, row.names = 1)

#reorder so all are in the correct order
tags.C1 <- tags.C1[order(row.names(tags.C1)),]
tags.C2 <- tags.C2[order(row.names(tags.C2)),]

counts.C1 <- counts.C1[order(row.names(counts.C1)),]
counts.C2 <- counts.C2[order(row.names(counts.C2)),]

#Check to make sure barcodes are in the same order for all 3 files
all(rownames(STreads.C2) == rownames(tags.C2))
all(rownames(STreads.C2) == rownames(counts.C2))

#create Seurat objects for each cartridge while transposing since BD output is opposite of Seurat input
data.C1 <- CreateSeuratObject(counts = t(counts.C1), project = "C1")
data.C2 <- CreateSeuratObject(counts = t(counts.C2), project = "C2")

#Add Sample_tags as metadata to the Seurat object
data.C1$Sample_tag <- cbind(tags.C1$Sample_Tag)
data.C2$Sample_tag <- cbind(tags.C2$Sample_Tag)

#Add Sample_tag reads as metadata to Seurat object
data.C1$ST2_reads <- cbind(STreads.C1$SampleTag02_mm.stAbO)
data.C1$ST3_reads <- cbind(STreads.C1$SampleTag03_mm.stAbO)
data.C1$ST4_reads <- cbind(STreads.C1$SampleTag04_mm.stAbO)
data.C1$ST5_reads <- cbind(STreads.C1$SampleTag05_mm.stAbO)
data.C1$ST6_reads <- cbind(STreads.C1$SampleTag06_mm.stAbO)
data.C1$ST7_reads <- cbind(STreads.C1$SampleTag07_mm.stAbO)
data.C1$ST8_reads <- cbind(STreads.C1$SampleTag08_mm.stAbO)
data.C1$ST9_reads <- cbind(STreads.C1$SampleTag09_mm.stAbO)

data.C2$ST2_reads <- cbind(STreads.C2$SampleTag02_mm.stAbO)
data.C2$ST3_reads <- cbind(STreads.C2$SampleTag03_mm.stAbO)
data.C2$ST4_reads <- cbind(STreads.C2$SampleTag04_mm.stAbO)
data.C2$ST5_reads <- cbind(STreads.C2$SampleTag05_mm.stAbO)
data.C2$ST6_reads <- cbind(STreads.C2$SampleTag06_mm.stAbO)
data.C2$ST7_reads <- cbind(STreads.C2$SampleTag07_mm.stAbO)
data.C2$ST8_reads <- cbind(STreads.C2$SampleTag08_mm.stAbO)
data.C2$ST9_reads <- cbind(STreads.C2$SampleTag09_mm.stAbO)

#find mitochondrial percentages: use pattern "^Mt." for rat, “^mt.” for mouse, “^MT.” for human
data.C1$percent_mt <- PercentageFeatureSet(data.C1, pattern = "^mt.")
data.C2$percent_mt <- PercentageFeatureSet(data.C2, pattern = "^mt.")

#filter out mitochondrial genes for downstream analysis
#data.C1 <- data.C1[!grepl("^mt\\.", rownames(data.C1)), ]
#data.C2 <- data.C2[!grepl("^mt\\.", rownames(data.C2)), ]
```