---
title: "F3_DEG"
author: "Katherine Savell"
date: "2023-03-20"
output: html_document
---

```{r}
library(dplyr)
library(purrr)
library(magrittr)
library(tester)
library(Matrix)
library(pbmcapply)
library(lmtest)
library(tidyselect)
library(DESeq2)
library(Seurat)
library(blme)
library(edgeR)
library(glmmTMB)
library(limma)
library(lme4)
library(lmerTest)
library(matrixStats)
library(methods)
library(stats)
library(Rdpack)
library(Libra)
library(pheatmap)
library(tibble)
```
###Glut
##Use Libra to generate count tables for DESeq2
Thank you @jordansquair! 
```{r}
#split into clusters
glut0 <- subset(glut.subset2, idents = "0")
glut1 <- subset(glut.subset2, idents = "1")
glut2 <- subset(glut.subset2, idents = "2")
glut3 <- subset(glut.subset2, idents = "3")
glut4 <- subset(glut.subset2, idents = "4")
glut5 <- subset(glut.subset2, idents = "5")

Idents(glut0) <- 'group'
Idents(glut1) <- 'group'
Idents(glut2) <- 'group'
Idents(glut3) <- 'group'
Idents(glut4) <- 'group'
Idents(glut5) <- 'group'

glut0 <- subset(glut0, idents = c("negative","positive"))
glut1 <- subset(glut1, idents = c("negative","positive"))
glut2 <- subset(glut2, idents = c("negative","positive"))
glut3 <- subset(glut3, idents = c("negative","positive"))
glut4 <- subset(glut4, idents = c("negative","positive"))
glut5 <- subset(glut5, idents = c("negative","positive"))

#Collapse into 1 cluster to run 'all glut' together
all.glut <- FindClusters(glut.subset2, resolution = 0)
Idents(all.glut) <- 'group'
all.glut <- subset(all.glut, idents = c("negative","positive"))
```

```{r}
pb <- to_pseudobulk(
  glut0, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts <- pb[["0"]] ##change this too

#generate metadata table ##FIX THIS
metadata <- read.csv("/Users/savellke/Documents/Analysis/mm10_exp1/March2023/metadata.csv", row.names = 1)

#check that the metadata is set up correctly
all(rownames(metadata) == colnames(counts))  
```

##DESeq2 
```{r}
dds <- DESeqDataSetFromMatrix(counts, 
                              colData = metadata, 
                              design = ~ group)

# perform quality control and filter out low-count genes
dds <- dds[ rowSums(counts(dds)) > 10, ]

dds <- DESeq(dds)

plotDispEsts(dds)

# By design, the first group listed is the "experimental" condition. 
contrast <- c("group", "positive", "negative")

# resultsNames(dds)
res0 <- results(dds, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

# Turn the results object into a tibble for use with tidyverse functions
res_tbl0 <- res0 %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

# Check results output
res_tbl0 ##change here

#res_tbl <- subset(res_tbl0, (res_tbl0$baseMean > 10))

# Write all results to file
write.csv(res_tbl, '/Users/savellke/Documents/Analysis/mm10_exp1/March2023/DESeqGlut5_PosNegDEGs_03232023.csv')

counts.norm <- counts(dds, normalized = T)
write.csv(counts.norm, '/Users/savellke/Documents/Analysis/mm10_exp1/DESeqGlut5_PosNegCounts_03232023.csv')
```
#QC
```{r}
# Transform counts for data visualization
rld <- rlog(dds, blind=TRUE)

# Plot PCA

DESeq2::plotPCA(rld, intgroup = "group")

# Extract the rlog matrix from the object and compute pairwise correlation values
rld_mat <- assay(rld)
rld_cor <- cor(rld_mat)

# Plot heatmap
pheatmap(rld_cor, annotation = metadata[, c("group", "sex"), drop=F])
```

###GABA
```{r}
#Collapse into 1 cluster to run 'all gaba' together
all.gaba <- FindClusters(gaba.subset2, resolution = 0)
Idents(all.gaba) <- 'group'
all.gaba <- subset(all.gaba, idents = c("negative","positive"))

pb <- to_pseudobulk(
  all.gaba,
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts <- pb[["0"]]

#generate metadata table ##FIX THIS
metadata <- read.csv("/Users/savellke/Documents/Analysis/mm10_exp1/March2023/metadata.csv", row.names = 1)

#check that the metadata is set up correctly
all(rownames(metadata) == colnames(counts))  
```

##Coexpression
glut v gaba
```{r}
coexp <- merge(res.glut, res.gaba, by='gene', all=TRUE, suffixes=c('_glut', '_gaba'))


coexp$keep[coexp$padj_glut < 0.05 | coexp$padj_gaba < 0.05] <- 1
coexp <- subset(coexp, coexp$keep == 1)
coexp <- subset(coexp, (coexp$baseMean_glut > 10))

#0.1 glut, 0.2 gaba, both
coexp$sig[(coexp$padj_glut <0.05)] <- .1
coexp$sig[(coexp$padj_gaba <0.05)] <- .2
coexp$sig[(coexp$padj_glut <0.05 & coexp$padj_gaba <0.05)] <- .3


write.csv(coexp, '/Users/savellke/Documents/Analysis/mm10_exp1/coexp.csv')
```
all glut vs cluster 0
```{r}
coexp <- merge(res_tbl, res_tbl0, by='gene', all=TRUE, suffixes=c('_a', '_0'))


coexp$keep[coexp$padj_a < 0.05 | coexp$padj_0 < 0.05] <- 1
coexp <- subset(coexp, coexp$keep == 1)

#0.1 glut, 0.2 gaba, both
coexp$sig[(coexp$padj_a <0.05)] <- .1
coexp$sig[(coexp$padj_0 <0.05)] <- .2
coexp$sig[(coexp$padj_a <0.05 & coexp$padj_0 <0.05)] <- .3


write.csv(coexp, '/Users/savellke/Documents/Analysis/mm10_exp1/coexp_alland0.csv')
```

#Dot Plots for caption
```{r}
Idents(glut.subset2) <- 'group'
dot.glut <- subset(glut.subset2, idents = c("negative","positive"))
dot.glut$cluster_group <- paste(dot.glut$seurat_clusters, 
                                    dot.glut$group,
                                    sep = "_")
coexp.genes <- c("Inhba","Gadd45b","Fosb","Homer1","Arc", "Bdnf","Scg2", "Nptx2","Prnp")
DotPlot(dot.glut, features = coexp.genes, scale = F, group.by = "cluster_group")

#change the order
Idents(dot.glut) <- 'cluster_group'
levels(dot.glut) <- c("1_negative","0_negative","2_negative","5_negative","4_negative","3_negative","1_positive","0_positive","2_positive","5_positive","4_positive","3_positive")

```

```{r}
test <- counts(dds, normalized = T)
```

