---
title: "S2"
author: "Kareem"
date: "2023-05-12"
output: html_document
---
#Load Packages
```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyverse)
```

#Load Object
```{r}
setwd("/Users/woodskad/Desktop/Analysis/S1/")
load("/Users/woodskad/Desktop/Analysis/S1/Robject/glut_subset_forthpipe_11102022.RData")
load("/Users/woodskad/Desktop/Analysis/S1/Robject/gaba_subset_forthpipe_03142023.RData")
```

#Subset Glut object
```{r}
Cart1g <- subset(x = glut.subset2, subset = orig.ident == "C1")
Cart2g <- subset(x = glut.subset2, subset = orig.ident == "C2")
```

#UMAP Glut Cartridge 1
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/S1_panels/GlutUMAP_Cart1.pdf",
    width = 10,
    height = 10)
DimPlot(Cart1g, 
        cols = c("#64C7C8", "#41B75F", "#2C8CB9", "#0A5B8C", "#3C9E64", "#6F499D" ), 
        shuffle = T) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```

#UMAP Glut Cartridge 2
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/S1_panels/GlutUMAP_Cart2.pdf",
    width = 10,
    height = 10)
DimPlot(Cart1g, 
        cols = c("#64C7C8", "#41B75F", "#2C8CB9", "#0A5B8C", "#3C9E64", "#6F499D" ), 
        shuffle = T) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```

#Glut:Fraction/Percent totals for Cart1/Cart2 
```{r}
glut.subset2$cluster_cart <- paste(glut.subset2$seurat_clusters,
                                   glut.subset2$orig.ident,
                                   sep = "_")
glut.subset2$cluster <- paste(glut.subset2$seurat_clusters)

df.glut.carts <- data.frame(table(glut.subset2$cluster_cart))
df.glut.clusters <- data.frame(table(glut.subset2$cluster))

df.glut.carts <- separate(df.glut.carts, col = Var1, into = c("cluster", "cart"), sep = "_")

df.glut.carts <- merge.data.frame(df.glut.carts, 
                                  df.glut.clusters,
                                  by.x = "cluster",
                                  by.y = "Var1", 
                                  all = TRUE)
df.glut.carts$Fraction <- (df.glut.carts$Freq.x/df.glut.carts$Freq.y)
df.glut.carts$Percent <- (df.glut.carts$Fraction * 100)

```

#GABA
#Subset Gaba object
```{r}
Cart1 <- subset(x = gaba.subset2, subset = orig.ident == "C1")
Cart2 <- subset(x = gaba.subset2, subset = orig.ident == "C2")
```

#UMAP Gaba Cartridge1
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/S1_panels/Gaba/GabaUMAP_Cart1.pdf",
    width = 10,
    height = 10)
DimPlot(Cart1,
        cols = c("#E66027", "#F8991D", "#C03C82", "#A669AB", "#C52126", "#DB808C", "#B0B235")) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```

#UMAP Gaba Cartridge2
```{r}
pdf(file = "/Users/woodskad/Library/CloudStorage/Box-Box/mRFP-snSeq/Project1_XPoSEseq/XPoSEseq_manuscript/S1_panels/Gaba/GabaUMAP_Cart2.pdf",
    width = 10,
    height = 10)
DimPlot(Cart2,
        cols = c("#E66027", "#F8991D", "#C03C82", "#A669AB", "#C52126", "#DB808C", "#B0B235"),
        shuffle = T) + 
  theme_void() + 
  theme(legend.position = "none") + 
  ggtitle(NULL)
dev.off()
```

#GABA:Fraction/Percent totals for Cart1/Cart2 
```{r}
gaba.subset2$cluster_cart <- paste(gaba.subset2$seurat_clusters,
                                   gaba.subset2$orig.ident,
                                   sep = "_")
gaba.subset2$cluster <- paste(gaba.subset2$seurat_clusters)

df.gaba.carts <- data.frame(table(gaba.subset2$cluster_cart))
df.gaba.clusters <- data.frame(table(gaba.subset2$cluster))

df.gaba.carts <- separate(df.gaba.carts, col = Var1, into = c("cluster", "cart"), sep = "_")

df.gaba.carts <- merge.data.frame(df.gaba.carts, 
                                  df.gaba.clusters,
                                  by.x = "cluster",
                                  by.y = "Var1", 
                                  all = TRUE)
df.gaba.carts$Fraction <- (df.gaba.carts$Freq.x/df.gaba.carts$Freq.y)
df.gaba.carts$Percent <- (df.gaba.carts$Fraction * 100)
```