---
title: "F3_DEG"
author: "Katherine Savell"
date: "2023-03-20"
output: html_document
---
##load packages
```{r message=FALSE}
library(dplyr)
library(purrr)
library(magrittr)
library(tester)
library(Matrix)
library(lmtest)
library(tidyselect)
library(DESeq2)
library(Seurat)
library(blme)
library(glmmTMB)
library(lme4)
library(lmerTest)
library(matrixStats)
library(methods)
library(stats)
library(Rdpack)
library(Libra)
library(pheatmap)
library(tibble)
library(UpSetR)
library(ComplexHeatmap)
library(ComplexUpset)
library(data.table)
```

##Split objects by group, only performed analysis on clusters when positive/negative was at least 30% and generally > 100 nuclei in each group
```{r message=FALSE}
#split into clusters, 4 and 5 do not have enough positives to analyze
glut0 <- subset(glut.subset2, idents = "0")
glut1 <- subset(glut.subset2, idents = "1")
glut2 <- subset(glut.subset2, idents = "2")
glut3 <- subset(glut.subset2, idents = "3")

Idents(glut0) <- 'group'
Idents(glut1) <- 'group'
Idents(glut2) <- 'group'
Idents(glut3) <- 'group'

glut0 <- subset(glut0, idents = c("negative","positive"))
glut1 <- subset(glut1, idents = c("negative","positive"))
glut2 <- subset(glut2, idents = c("negative","positive"))
glut3 <- subset(glut3, idents = c("negative","positive"))

#Collapse into 1 cluster to run 'all glut' together
all.glut <- FindClusters(glut.subset2, resolution = 0)
Idents(all.glut) <- 'group'
all.glut <- subset(all.glut, idents = c("negative","positive"))

#gaba
gaba0 <- subset(gaba.subset2, idents = "0")
gaba1 <- subset(gaba.subset2, idents = "1")
gaba4 <- subset(gaba.subset2, idents = "4")

Idents(gaba0) <- 'group'
Idents(gaba1) <- 'group'
Idents(gaba4) <- 'group'

gaba0 <- subset(gaba0, idents = c("negative","positive"))
gaba1 <- subset(gaba1, idents = c("negative","positive"))
gaba4 <- subset(gaba4, idents = c("negative","positive"))

all.gaba <- FindClusters(gaba.subset2, resolution = 0)
Idents(all.gaba) <- 'group'
all.gaba <- subset(all.gaba, idents = c("negative","positive"))

```
##Generate count tables for DESeq2
Thank you @jordansquair! for Libra
```{r}
##All glut combined
pba <- to_pseudobulk(
  all.glut, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
countsa <- pba[["0"]] ##change this too

##Cluster 0
pb0 <- to_pseudobulk(
  glut0, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts0 <- pb0[["0"]] ##change this too

##Cluster 1
pb1 <- to_pseudobulk(
  glut1, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts1 <- pb1[["1"]] ##change this too

##Cluster 2
pb2 <- to_pseudobulk(
  glut2, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts2 <- pb2[["2"]] ##change this too

##Cluster 3
pb3 <- to_pseudobulk(
  glut3, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts3 <- pb3[["3"]] ##change this too

##All gaba combined
pbag <- to_pseudobulk(
  all.gaba, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
countsag <- pbag[["0"]] ##change this too

##Cluster 0
pb0g <- to_pseudobulk(
  gaba0, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#subset the cluster to test, here they are combined into one called "0"
counts0g <- pb0g[["0"]] ##change this too

##Cluster 1
pb1g <- to_pseudobulk(
  gaba1, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#counts
counts1g <- pb1g[["1"]] ##change this too

##Cluster 4
pb4g <- to_pseudobulk(
  gaba4, ##change here
  replicate_col = "ratID",
  cell_type_col = "seurat_clusters", #this is required, could merge as 1 to run
  label_col = "group"
)
#counts
counts4g <- pb4g[["4"]] ##change this too

#generate metadata table ##FIX THIS
metadata <- read.csv("/Users/savellke/Documents/Analysis/mm10_exp1/March2023/metadata.csv", row.names = 1)

#check that the metadata is set up correctly
all(rownames(metadata) == colnames(counts))  

```
## Run DESeq2
```{r message=FALSE}
# By design, the first group listed is the "experimental" condition. 
contrast <- c("group", "positive", "negative")

#Cluster all
ddsa <- DESeqDataSetFromMatrix(countsa, 
                              colData = metadata, 
                              design = ~ group)

ddsa <- ddsa[ rowSums(counts(ddsa)) > 5, ]

ddsa <- DESeq(ddsa)

resa <- results(ddsa, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbla <- resa %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 0
dds0 <- DESeqDataSetFromMatrix(counts0, 
                              colData = metadata, 
                              design = ~ group)

dds0 <- dds0[ rowSums(counts(dds0)) > 5, ]

dds0 <- DESeq(dds0)

res0 <- results(dds0, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl0 <- res0 %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 1
dds1 <- DESeqDataSetFromMatrix(counts1, 
                              colData = metadata, 
                              design = ~ group)

dds1 <- dds1[ rowSums(counts(dds1)) > 5, ]

dds1 <- DESeq(dds1)

res1 <- results(dds1, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl1 <- res1 %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 2
dds2 <- DESeqDataSetFromMatrix(counts2, 
                              colData = metadata, 
                              design = ~ group)

dds2 <- dds2[ rowSums(counts(dds2)) > 5, ]

dds2 <- DESeq(dds2)

res2 <- results(dds2, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl2 <- res2 %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 3
dds3 <- DESeqDataSetFromMatrix(counts3, 
                              colData = metadata, 
                              design = ~ group)

dds3 <- dds3[ rowSums(counts(dds3)) > 5, ]

dds3 <- DESeq(dds3)

res3 <- results(dds3, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl3 <- res3 %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster all
ddsag <- DESeqDataSetFromMatrix(countsag, 
                              colData = metadata, 
                              design = ~ group)

ddsag <- ddsag[ rowSums(counts(ddsag)) > 5, ]

ddsag <- DESeq(ddsag)

resag <- results(ddsag, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tblag <- resag %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 0
dds0g <- DESeqDataSetFromMatrix(counts0g, 
                              colData = metadata, 
                              design = ~ group)

dds0g <- dds0g[ rowSums(counts(dds0g)) > 5, ]

dds0g <- DESeq(dds0g)

res0g <- results(dds0g, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl0g <- res0g %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 1
dds1g <- DESeqDataSetFromMatrix(counts1g, 
                              colData = metadata, 
                              design = ~ group)

dds1g <- dds1g[ rowSums(counts(dds1g)) > 5, ]

dds1g <- DESeq(dds1g)

res1g <- results(dds1g, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl1g <- res1g %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()

#Cluster 4
dds4g <- DESeqDataSetFromMatrix(counts4g, 
                              colData = metadata, 
                              design = ~ group)

dds4g <- dds4g[ rowSums(counts(dds4g)) > 2, ]

dds4g <- DESeq(dds4g)

res4g <- results(dds4g, ##change here
               contrast = contrast,
               alpha = 0.05,
               pAdjustMethod = "fdr")

res_tbl4g <- res4g %>% ##change here
        data.frame() %>%
        rownames_to_column(var="gene") %>%
        as_tibble()
```

#Generating coexpression table as input for UpSet
```{r}
ce <- merge(res_tbla, res_tbl0, 
            by='gene', 
            all=TRUE, 
            suffixes=c('_a', '_0')) 
ce1 <- merge(res_tbl1, res_tbl2, 
             by='gene', 
             all=TRUE, 
             suffixes=c('_1', '_2')) 
ce2 <- merge(res_tbl3, res_tblag, 
             by='gene', 
             all=TRUE, 
             suffixes=c('_3', '_ag'))
ce3 <- merge(res_tbl0g, res_tbl1g, 
             by='gene', 
             all=TRUE, 
             suffixes=c('_0g', '_1g'))
        
ce4 <- merge(ce, ce1, 
             by='gene', 
             all=TRUE, 
             no.dups = TRUE)
ce5 <- merge(ce2, ce3, 
             by ='gene', 
             all=TRUE, 
             no.dups = TRUE) 
coexp <- merge(ce4, ce5, 
               by ='gene', 
               all=TRUE, 
               no.dups = TRUE)


write.csv(coexp, '/Users/savellke/Documents/Analysis/mm10_exp1/coexp_03312023.csv')

#filter by sig
coexp$keep[coexp$padj_a < 0.05 | coexp$padj_0 < 0.05 | coexp$padj_1 < 0.05 | coexp$padj_2 < 0.05 | coexp$padj_3 < 0.05 | coexp$padj_ag < 0.05 | coexp$padj_0g < 0.05 | coexp$padj_1g < 0.05] <- 1 
coexp <- subset(coexp, coexp$keep == 1)
```

#Upset plot by ComplexHeatmap and ComplexUpSet, thanks @jokergoo! 
```{r}
#up
df <- data.frame(coexp$gene)
rownames(df) <- df$coexp.gene
df <- df[,-1]

df$up1[(coexp$padj_1 <0.05 & coexp$log2FoldChange_1 > 0)] <- 1
df$up0[(coexp$padj_0 <0.05 & coexp$log2FoldChange_0 > 0)] <- 1
df$up2[(coexp$padj_2 <0.05 & coexp$log2FoldChange_2 > 0)] <- 1
df$up3[(coexp$padj_3 <0.05 & coexp$log2FoldChange_3 > 0)] <- 1
df$up0g[(coexp$padj_0g <0.05 & coexp$log2FoldChange_0g > 0)] <- 1
df$up1g[(coexp$padj_1g <0.05 & coexp$log2FoldChange_1g > 0)] <- 1

#fill in NA as zero
df[is.na(df)] <- 0

#down
dfd <- data.frame(coexp$gene)
rownames(dfd) <- dfd$coexp.gene
dfd <- dfd[,-1]

dfd$dn1[(coexp$padj_1 <0.05 & coexp$log2FoldChange_1 < 0)] <- 1
dfd$dn0[(coexp$padj_0 <0.05 & coexp$log2FoldChange_0 < 0)] <- 1
dfd$dn2[(coexp$padj_2 <0.05 & coexp$log2FoldChange_2 < 0)] <- 1
dfd$dn3[(coexp$padj_3 <0.05 & coexp$log2FoldChange_3 < 0)] <- 1
dfd$dn0g[(coexp$padj_0g <0.05 & coexp$log2FoldChange_0g < 0)] <- 1
#dfd$dn1g[(coexp$padj_1g <0.05 & coexp$log2FoldChange_1g < 0)] <- 1

dfd[is.na(dfd)] <- 0



#make combination matrix, distinct is mutually exclusive
cm <- make_comb_mat(df,
                    mode = c("distinct"))
cm <- cm[, -c(26)]

cmd <- make_comb_mat(dfd,
                    mode = c("distinct"))
cmd <- cmd[, -c(18)]

#
UpSet(t(cm))
      
      ,
      set_order = c("up3","up1","up0","up2","up4",
                    "dn3","dn1","dn0","dn2","dn4"),
      comb_order = c(1,3,4,5,6,11,12,13,14,15,16,17,
                     2,7,8,9,10,18,19,20,21,22,23))

UpSet(t(cm),
      )
```
```{r}
pdf(file = "/Users/savellke/Output/UpSetUP.pdf",
    width = 4,
    height = 4)
UpSet(t(cm))
dev.off()
```

